Feat/main page
aydik99/twitter-demo-frontend pull request #1
Opened 2018-06-20 07:30 UTC by aydik99

2018-06-20 07:38 UTC, aydik99 commented
Забыл убрать папку image/.

2018-06-20 21:40 UTC, imevro requested changes

2018-06-20 21:40 UTC, evgenyrodionov commented on package.json
> +    "editor.formatOnPaste": true,
что тут делают настройки вскода?

2018-06-20 21:40 UTC, evgenyrodionov commented on public/normalize.css
> +/*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
зачем это тут? ставь из нпма и импорти в своём приложении

2018-06-20 21:40 UTC, evgenyrodionov commented on src/App.js
> +import createBrowserHistory from "history/createBrowserHistory";
это что и для чего?

2018-06-20 21:40 UTC, evgenyrodionov commented on src/Banner/index.js
> +      <div>
зачем тут див?

2018-06-20 21:40 UTC, evgenyrodionov commented on src/Banner/index.js
> +class Banner extends Component {
зачем ты используешь классы?

2018-06-20 21:40 UTC, evgenyrodionov commented on src/Header/index.js
> +  letter-spacing: 0.1px;
нет

2018-06-20 21:40 UTC, evgenyrodionov commented on src/Header/index.js
> +                <NavLinkMenu to="#">Home</NavLinkMenu>
преттир не настроен — не могу дальше проверять

2018-06-22 21:18 UTC, evgenyrodionov commented
что с коммитами? какие лессон 2? что значит корректед?

2018-06-22 21:22 UTC, imevro requested changes
преттир все еще не настроен, НЕ МОГУ ПРОВЕРЯТЬ ЕСЛИ КОДСТАЙЛ НЕ СОБЛЮДАЕТСЯ, В ОЧЕРЕДНОЙ РАЗ ПОВТОРЯЮ

и верстка ужасная, какие-то флоаты, отрицательные марджины и тд

2018-06-22 21:22 UTC, evgenyrodionov commented on package.json
>      "prettier.eslintIntegration": true,
а это?

2018-06-22 21:22 UTC, evgenyrodionov commented on public/images/users/5.svg
> +<image id="image0" width="512" height="512" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAAAXNSR0IArs4c6QAALGVJREFUeAHt3QecXGW5P/A3jfRGOjUJgQAJoRdFlCooShMpFiyACCqgX
это же пнг, зачем ты тянешь как свг? остальных файлов тоже касается

2018-06-22 21:22 UTC, evgenyrodionov commented on src/App.js
> +import createBrowserHistory from 'history/createBrowserHistory'
я так и не понял что это и зачем это

2018-06-22 21:22 UTC, evgenyrodionov commented on src/Followers/FollowerUser.js
> +const followerUserSvg = $img =>
какая разница свг или пнг?

2018-06-22 21:22 UTC, evgenyrodionov commented on src/Followers/FollowerUser.js
> +const followerUserSvg = $img =>
зачем доллар? это не пхп

2018-06-22 21:22 UTC, evgenyrodionov commented on src/Followers/FollowerUser.js
> +const followerUserSvg = $img =>
название функции должно быть глаголом, фолловер юзер свг вообще ничего не говорит о том что делает эта функция

2018-06-22 21:22 UTC, evgenyrodionov commented on src/Followers/index.js
> +    to: '#'
ссылки не будут приходить с сервера

2018-06-22 21:22 UTC, evgenyrodionov commented on src/Followers/index.js
> +    img: '5',
а полный путь до пикчи будет

2018-06-22 21:22 UTC, evgenyrodionov commented on src/ListPosts/TweetItem.js
> +  float: left;
откуда взялись флоаты? мы не в 2001 году

2018-06-22 21:22 UTC, evgenyrodionov commented on src/ListPosts/TweetItem.js
> +  left: 3px;
что это за хаки?

2018-06-22 21:22 UTC, evgenyrodionov commented on src/ListPosts/TweetItem.js
> +  margin: -20px 0 0 0;
а это?

2018-06-22 21:22 UTC, evgenyrodionov commented on src/ListPosts/TweetItem.js
> +  width: 420px;
откуда ширина у дива?

2018-06-23 20:23 UTC, aydik99 commented
Не успел убрать маржины и флоуты только. Их обязательно уберу и использую флексы. Остальное исправил.  Странно на счет оформления.  Даже при мне  стиль код стал структурированным на глазах, когда вбивал команду "npx prettier --write src/**.*.js".

2018-06-25 15:55 UTC, closed without merging

2018-06-25 15:55 UTC, evgenyrodionov commented
Напиши мне в телеграм, дам доступ в курсач